**Compute gripper rotation matrix from arm joints present position**

In [1]:
from reachy_sdk import ReachySDK
from reachy_sdk.trajectory import goto
from scipy.spatial.transform import Rotation as R
import numpy as np

reachy = ReachySDK(host='localhost')

In [3]:
r1 = R.from_euler('y', np.deg2rad(reachy.r_arm.r_shoulder_pitch.present_position))
r2 = R.from_euler('x', np.deg2rad(reachy.r_arm.r_shoulder_roll.present_position))
r3 = R.from_euler('z', np.deg2rad(reachy.r_arm.r_arm_yaw.present_position))
r4 = R.from_euler('y', np.deg2rad(reachy.r_arm.r_elbow_pitch.present_position))
r5 = R.from_euler('z', np.deg2rad(reachy.r_arm.r_forearm_yaw.present_position))
r6 = R.from_euler('y', np.deg2rad(reachy.r_arm.r_wrist_pitch.present_position))
r7 = R.from_euler('x', np.deg2rad(reachy.r_arm.r_wrist_roll.present_position))
r = r1 * r2 * r3 * r4 * r5* r6 * r7


In [4]:
print(reachy.r_arm.forward_kinematics())

[[ 0.07757835 -0.46280197 -0.88306055  0.30879002]
 [ 0.05844804  0.88631773 -0.45937426 -0.11488889]
 [ 0.99527153 -0.01597566  0.09580894 -0.39461339]
 [ 0.          0.          0.          1.        ]]


In [5]:
print(r.as_matrix())

[[ 0.07764797 -0.46403135 -0.88240903]
 [ 0.0584618   0.88567746 -0.46060574]
 [ 0.9952653  -0.01582212  0.09589916]]
