# Prise en main de Reachy

**Imports utiles:**

In [1]:
from reachy_sdk import ReachySDK
from reachy_sdk.trajectory import goto

**Declaration de l'objet Reachy**

In [2]:
reachy = ReachySDK(host='localhost') #ou ip=***.**.**.*

In [3]:
import time
import numpy as np
from scipy.spatial.transform import Rotation as R

**Affichage de l'etat des joints**

In [8]:
print(reachy.joints)

<Holder
	<Joint name="r_shoulder_pitch" pos="20.60" mode="compliant">
	<Joint name="r_shoulder_roll" pos="4.16" mode="compliant">
	<Joint name="r_arm_yaw" pos="0.31" mode="compliant">
	<Joint name="r_elbow_pitch" pos="-81.36" mode="compliant">
	<Joint name="r_forearm_yaw" pos="8.94" mode="compliant">
	<Joint name="r_wrist_pitch" pos="-23.87" mode="compliant">
	<Joint name="r_wrist_roll" pos="12.76" mode="compliant">
	<Joint name="r_gripper" pos="-57.33" mode="compliant">
>


**Affichage de la matrice de pose du gripper droit**

In [11]:
print(reachy.r_arm.forward_kinematics())

[[ 0.08306464 -0.5215218  -0.84918507  0.31732196]
 [ 0.04126262  0.85319903 -0.51995077 -0.04287087]
 [ 0.99568954  0.00814992  0.09239002 -0.27461295]
 [ 0.          0.          0.          1.        ]]


**Allumage et extinction du bras droit de Reachy**

In [4]:
reachy.turn_on('r_arm')
reachy.turn_off_smoothly('r_arm') 

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/reachy/dev/reachy-sdk/reachy_sdk/reachy_sdk.py", line 176, in _start_sync_in_bg
    loop.run_until_complete(self._sync_loop())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/reachy/dev/reachy-sdk/reachy_sdk/reachy_sdk.py", line 231, in _sync_loop
    await asyncio.gather(
  File "/home/reachy/dev/reachy-sdk/reachy_sdk/reachy_sdk.py", line 186, in _get_stream_update_loop
    async for state_update in joint_stub.StreamJointsState(stream_req):
  File "/home/reachy/.local/lib/python3.8/site-packages/grpc/aio/_call.py", line 321, in _fetch_stream_responses
    await self._raise_for_status()
  File "/home/reachy/.local/lib/python3.8/site-packages/gr

**Envoi concis d'une commande a partir de la liste joint_pos des positions des joints**

In [ ]:
goto(goal_positions={joint: pos for joint,pos in zip(reachy.r_arm.joints.values(), joint_pos)}, duration=1.0)

**Envoi d'une commande a partir d'un dictionnaire avec choix d'un mode d'interpollation**

In [ ]:
q = {
    reachy.r_arm.r_shoulder_pitch: 0,
    reachy.r_arm.r_shoulder_roll: 0,
    reachy.r_arm.r_arm_yaw: 0,
    reachy.r_arm.r_elbow_pitch: 0,
    reachy.r_arm.r_forearm_yaw: 0,
    reachy.r_arm.r_wrist_pitch: 0,
    reachy.r_arm.r_wrist_roll: 0,
}
goto(q, duration=1.0, interpolation_mode=InterpolationMode.MINIMUM_JERK)

**Mettre compliant un joint en particulier (ici r_wrist_pitch)**

In [ ]:
reachy.r_arm.r_wrist_pitch.compliant = True

**Assignier une valeur a un joint en particulier (ici r_elbow_pitch)**

In [5]:
reachy.r_arm.r_elbow_pitch.goal_position = 50