In [1]:
from reachy_sdk import ReachySDK
from reachy_sdk.trajectory import goto
reachy = ReachySDK(host='localhost')

In [3]:
import time
import numpy as np
from scipy.spatial.transform import Rotation as R

In [6]:
print(reachy.joints)

<Holder
	<Joint name="r_shoulder_pitch" pos="-11.67" mode="compliant">
	<Joint name="r_shoulder_roll" pos="2.13" mode="compliant">
	<Joint name="r_arm_yaw" pos="3.38" mode="compliant">
	<Joint name="r_elbow_pitch" pos="-91.03" mode="compliant">
	<Joint name="r_forearm_yaw" pos="-4.25" mode="compliant">
	<Joint name="r_wrist_pitch" pos="9.98" mode="compliant">
	<Joint name="r_wrist_roll" pos="6.01" mode="compliant">
	<Joint name="r_gripper" pos="17.16" mode="compliant">
>


In [6]:
recorded_joints = [
            reachy.r_arm.r_shoulder_pitch,
            reachy.r_arm.r_shoulder_roll,
            reachy.r_arm.r_arm_yaw,
            reachy.r_arm.r_elbow_pitch,
            reachy.r_arm.r_forearm_yaw,
            reachy.r_arm.r_wrist_pitch,
            reachy.r_arm.r_wrist_roll,
        ]
trajectories = [[-6.83, -6.48, 41.54, -82.51, -11, -7.96, 45.01, 18.62], [-7.36, 1.87, 41.27, -76.97, -3.67, -7.16, 38.27, 18.62], [-21.08, 2.66, 60.97, -66.51, -15.40, -14.55, 30.35, 15.40], [-23.71, 16.29, 60.97, -60.42, -10.70, -21.58, 25.95, 15.10], [-32.77, 13.47, 61.14, -43.21, -18.04, -24.04, 28.89, 18.62], [-25.91, 3.10, 57.71, -59.74, -15.98, -16.66, 24.78, 13.34], [-22.22, -12.72, 57.63, -72.31, -21.55, -20.44, 23.02, 13.93]]
point = []
point.append(dict(zip(recorded_joints, trajectories[0])))
point.append(dict(zip(recorded_joints, trajectories[1])))
point.append(dict(zip(recorded_joints, trajectories[2])))
point.append(dict(zip(recorded_joints, trajectories[3])))
point.append(dict(zip(recorded_joints, trajectories[4])))
point.append(dict(zip(recorded_joints, trajectories[5])))
point.append(dict(zip(recorded_joints, trajectories[6])))

# Goes to the start of the trajectory in 3s
reachy.turn_on('r_arm')
for i in range(7):
    goto(point[i], duration=1.0)
    time.sleep(1)
# goto(B_point, duration=1.0)
# time.sleep(1)

reachy.turn_off_smoothly('r_arm')   

In [2]:
reachy.turn_off_smoothly('r_arm')  

In [9]:
re = reachy.r_arm.forward_kinematics()
print(re)
print(R.from_matrix(re[:3,:3]).as_euler('xyz',degrees=True))

[[ 0.09758459 -0.07905969 -0.99208206  0.27631409]
 [ 0.02609731  0.99670024 -0.0768607  -0.18966611]
 [ 0.99488501 -0.01839026  0.09932583 -0.41255095]
 [ 0.          0.          0.          1.        ]]
[-10.4895723  -84.20243777  14.97238773]


In [28]:
re = reachy.r_arm.forward_kinematics()
print(re)
print(R.from_matrix(re[:3,:3]).as_euler('xyz',degrees=True))

[[ 0.0012022  -0.75333626 -0.65763442  0.14469907]
 [-0.0345694   0.65721052 -0.75291387 -0.01535689]
 [ 0.99940158  0.02363918 -0.02525228 -0.38707211]
 [ 0.          0.          0.          1.        ]]
[136.8897104  -88.01772668 -88.0082644 ]


In [ ]:
joint = reachy.joints

In [36]:
M = [np.array([[0, -0.66, -0.75,  0.39],
 [0,  0.75, -0.66,  0.15],
 [1,  0,  0, -0.23],
 [0,  0,  0,  1]]),
# np.array([[0, -0.98,  0.16,  0.15],
#  [0, 0.17, -0.98,  -0.06],
#  [1,  0, 0, -0.3],
#  [0, 0,  0,  1]]),
# np.array([[0, -0.66, -0.75,  0.39],
#  [0,  0.75, -0.66,  0.04],
#  [1,  0,  0, -0.23],
#  [0,  0,  0,  1]]),
# np.array([[0, -0.69,  -0.71,  0.44],
#  [0, 0.71, -0.69,  0.089],
#  [1,  0, 0, -0.22],
#  [0, 0,  0,  1]])
# np.array([[-0.07979978, -0.99338745, -0.08254311,  0.28355001],
#  [-0.07562723,  0.08860207, -0.99319192,  0.14130835],
#  [ 0.99393788, -0.07301399, -0.08219757, -0.29623623],
#  [ 0.,          0.,          0.,          1.,        ]]),
# np.array([[-0.08654919, -0.9943777,  -0.0610101,   0.28246602],
#  [-0.04173412,  0.064805,   -0.99702486,  0.18686002],
#  [ 0.99537305, -0.08374549, -0.0471083,  -0.26],
#  [ 0.,          0.,          0.,          1.,        ]]),
# np.array([[ 0.03841574, -0.99477811, -0.09455547,  0.2617683 ],
#  [-0.11786281,  0.08945399, -0.98899259,  0.18589666],
#  [ 0.99228655,  0.04913746, -0.11381091, -0.28313679],
#  [ 0.,          0.,          0.,          1.        ]]),
# np.array([[-0.1314988,  -0.94107359, -0.31159036,  0.35870463],
#  [-0.0250321,   0.31737182, -0.94797074,  0.07300856],
#  [ 0.99100023, -0.11685725, -0.06529106, -0.2981114 ],
#  [ 0.,          0.,          0.,          1.        ]]),
# np.array([[-0.07727944, -0.97297042, -0.21761539,  0.33970549],
#  [ 0.00556261,  0.21784396, -0.97596776, -0.01811426],
#  [ 0.99699395, -0.07663275, -0.01142261, -0.31127106],
#  [ 0.,          0.,          0.,          1.,        ]])
]

A = np.array([[0, -0.66, -0.75,  0.39-0.01],
 [0,  0.75, -0.66,  0.095-0.1],
 [1,  0,  0, -0.23],
 [0,  0,  0,  1]])

reachy.turn_on('r_arm')
# q = {"r_shoulder_pitch":-25.82, "r_shoulder_roll": -9.47, "r_arm_yaw": 59.38, "r_elbow_pitch": -72.22, "r_forearm_yaw": -15.69, "r_wrist_pitch": -3.21, "r_wrist_roll": 18.91}
# joint_pos_init = reachy.r_arm.inverse_kinematics(A)
# q = {
#     reachy.r_arm.r_shoulder_pitch: joint_pos_init[0],
#     reachy.r_arm.r_shoulder_roll: joint_pos_init[1],
#     reachy.r_arm.r_arm_yaw: joint_pos_init[2],
#     reachy.r_arm.r_elbow_pitch: joint_pos_init[3],
#     reachy.r_arm.r_forearm_yaw: joint_pos_init[4],
#     reachy.r_arm.r_wrist_pitch: joint_pos_init[5],
#     reachy.r_arm.r_wrist_roll: joint_pos_init[6],
# }

for mat in M:
    print(mat)
    joint_pos = reachy.r_arm.inverse_kinematics(mat)
    print('joint_theo= ' + str(joint_pos))
    print(reachy.r_arm.forward_kinematics(joint_pos))
    goto(goal_positions={joint: pos for joint,pos in zip(reachy.r_arm.joints.values(), joint_pos)}, duration=1.0) #, starting_positions=q)
    time.sleep(5)
    re = reachy.r_arm.forward_kinematics()
    print(reachy.joints)
    print(re)
#     M[1][3] = M[1][3] + 0.05
reachy.turn_off_smoothly('r_arm')

[[ 0.   -0.66 -0.75  0.39]
 [ 0.    0.75 -0.66  0.15]
 [ 1.    0.    0.   -0.23]
 [ 0.    0.    0.    1.  ]]
joint_theo= [-22.364774560371558, 24.861158684633605, 31.25472230715299, -59.01309897420809, 7.756902735575436, 1.1380022285877975, 3.001204527200582]
[[ 5.17838485e-05 -6.60371866e-01 -7.50938743e-01  3.89999851e-01]
 [ 3.38164108e-05  7.50938745e-01 -6.60371865e-01  1.49999928e-01]
 [ 9.99999998e-01  8.80254360e-06  6.12179045e-05 -2.29999977e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
<Holder
	<Joint name="r_shoulder_pitch" pos="-19.32" mode="stiff">
	<Joint name="r_shoulder_roll" pos="8.20" mode="stiff">
	<Joint name="r_arm_yaw" pos="30.11" mode="stiff">
	<Joint name="r_elbow_pitch" pos="-57.89" mode="stiff">
	<Joint name="r_forearm_yaw" pos="7.48" mode="stiff">
	<Joint name="r_wrist_pitch" pos="1.19" mode="stiff">
	<Joint name="r_wrist_roll" pos="3.96" mode="stiff">
	<Joint name="r_gripper" pos="-7.77" mode="stiff">
>
[[ 0.09334937 -0.58560374 -

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/reachy/dev/reachy-sdk/reachy_sdk/reachy_sdk.py", line 176, in _start_sync_in_bg
    loop.run_until_complete(self._sync_loop())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/reachy/dev/reachy-sdk/reachy_sdk/reachy_sdk.py", line 231, in _sync_loop
    await asyncio.gather(
  File "/home/reachy/dev/reachy-sdk/reachy_sdk/reachy_sdk.py", line 186, in _get_stream_update_loop
    async for state_update in joint_stub.StreamJointsState(stream_req):
  File "/home/reachy/.local/lib/python3.8/site-packages/grpc/aio/_call.py", line 321, in _fetch_stream_responses
    await self._raise_for_status()
  File "/home/reachy/.local/lib/python3.8/site-packages/gr

In [30]:
M = np.array([[ 0.116, -0.98, -0.14,   0.10],
 [-0.018,  0.14, -0.99,  -0.01], #0.05
 [ 0.99,  0.12, -0.002,  -0.25],
 [ 0.,          0.,          0.,          1.        ]])
reachy.turn_on('r_arm')

for i in range(9):
    print(M)
    joint_pos = reachy.r_arm.inverse_kinematics(M)
    goto(goal_positions={joint: pos for joint,pos in zip(reachy.r_arm.joints.values(), joint_pos)}, duration=1.0) #, starting_positions=q)
    time.sleep(2)
    re = reachy.r_arm.forward_kinematics()
    print(re)
    M[0][3]+=0.05
#     M[1][3] = M[1][3] + 0.05
reachy.turn_off_smoothly('r_arm')

[[ 0.116 -0.98  -0.14   0.1  ]
 [-0.018  0.14  -0.99  -0.01 ]
 [ 0.99   0.12  -0.002 -0.25 ]
 [ 0.     0.     0.     1.   ]]
[[ 0.14134169 -0.97705829 -0.15930985  0.10695501]
 [ 0.0395337   0.16636789 -0.98527093 -0.01362231]
 [ 0.98917117  0.13296175  0.06214145 -0.27114671]
 [ 0.          0.          0.          1.        ]]
[[ 0.116 -0.98  -0.14   0.15 ]
 [-0.018  0.14  -0.99  -0.01 ]
 [ 0.99   0.12  -0.002 -0.25 ]
 [ 0.     0.     0.     1.   ]]
[[ 0.1457987  -0.98072507 -0.13008101  0.1450774 ]
 [ 0.01618665  0.1338332  -0.99087167 -0.00868693]
 [ 0.98918185  0.14236223  0.03538736 -0.26274477]
 [ 0.          0.          0.          1.        ]]
[[ 0.116 -0.98  -0.14   0.2  ]
 [-0.018  0.14  -0.99  -0.01 ]
 [ 0.99   0.12  -0.002 -0.25 ]
 [ 0.     0.     0.     1.   ]]
[[ 0.16414468 -0.97633006 -0.14084084  0.19158292]
 [ 0.01371567  0.14502256 -0.98933328 -0.00500886]
 [ 0.98634092  0.16046207  0.0371957  -0.2657741 ]
 [ 0.          0.          0.          1.        ]]
[[ 0.116 -

In [54]:
reachy.turn_off_smoothly('r_arm')  

In [20]:
print(reachy.joints)

TypeError: 'DeviceHolder' object is not callable

In [31]:
reachy.r_arm.r_wrist_pitch.compliant = True

In [28]:
reachy.r_arm.r_wrist_roll.compliant = True

In [19]:
d = -91.3

In [51]:
p = reachy.r_arm.r_elbow_pitch.present_position

In [52]:
e = d - p
print(e)
kp = 1
c = p + kp*e
print(c)
print(p)

-1.759999999999991
-91.3
-89.54


In [49]:
reachy.turn_on("r_arm")

In [53]:
reachy.r_arm.r_elbow_pitch.goal_position = c

In [24]:
import numpy as np

In [25]:
np.rad2deg(-0.95)

-54.4309905374282

In [27]:
np.rad2deg(0.61)

34.95042550298022

In [4]:
with open('datas_id.npy', 'rb') as f:

    a = np.load(f)

print(a)

[[[21. 18. 15.]
  [ 6.  9. 12.]
  [24.  3.  0.]]

 [[22. 19. 16.]
  [ 7. 10. 13.]
  [25.  4.  1.]]

 [[23. 20. 17.]
  [ 8. 11. 14.]
  [26.  5.  2.]]]
